interval: 15s
minTimeOut: 1m
interfaces:
  - name: wg0
    address: 192.168.44.1/24
    target: mark_wg0
    mark: 0xa0
    counter: true
    wireguard: true
    wgpeer: somekey=
    wgMaxHandshake: 2m
    ratio: 3
  - name: br0
    address: 192.168.0.183/24
    target: mark_wg1
    ratio: 7
    mark: 0xa2
    checks:
    - name: check_gw_ssh
      type: tcp
      host: 192.168.0.2
      port: 22
      timeout: 500ms
      retries: 2
    - name: ping_gateway
      type: icmp
      host: 192.168.43.50
      timeout: 2s
      count: 5
      interval: 100ms
      maxrtt: 90
      maxlosspcnt: 20
    - name: check_haproxy
      type: http
      host: libretechconsulting.com
      tls: true
      insecure: false
      timeout: 5s
      method: GET
      path: /
      matchRegEx: "Libre"
      responseCode: 200

lbtable:
  family: ip
  name: mangle
lbchain: load_balance
